// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqEVFPu8gUah74LNhrTO2BxI103lvaQr8',
    appId: '1:972142974439:web:f8f0a3b6a3cd2ed2d4d942',
    messagingSenderId: '972142974439',
    projectId: 'pantrychef-bce0b',
    authDomain: 'pantrychef-bce0b.firebaseapp.com',
    storageBucket: 'pantrychef-bce0b.firebasestorage.app',
    measurementId: 'G-8JE36XYYYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD88yQyB1K4m0nBNkfq4qgsR83SmKo-1w8',
    appId: '1:972142974439:android:687a21ff3441d0ecd4d942',
    messagingSenderId: '972142974439',
    projectId: 'pantrychef-bce0b',
    storageBucket: 'pantrychef-bce0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RQ1MLvcwyRkYHV1fTHYLMUPamW3nhh0',
    appId: '1:972142974439:ios:6235d570d371c729d4d942',
    messagingSenderId: '972142974439',
    projectId: 'pantrychef-bce0b',
    storageBucket: 'pantrychef-bce0b.firebasestorage.app',
    iosBundleId: 'com.example.pantrychef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RQ1MLvcwyRkYHV1fTHYLMUPamW3nhh0',
    appId: '1:972142974439:ios:6235d570d371c729d4d942',
    messagingSenderId: '972142974439',
    projectId: 'pantrychef-bce0b',
    storageBucket: 'pantrychef-bce0b.firebasestorage.app',
    iosBundleId: 'com.example.pantrychef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqEVFPu8gUah74LNhrTO2BxI103lvaQr8',
    appId: '1:972142974439:web:a2446489cd1f387dd4d942',
    messagingSenderId: '972142974439',
    projectId: 'pantrychef-bce0b',
    authDomain: 'pantrychef-bce0b.firebaseapp.com',
    storageBucket: 'pantrychef-bce0b.firebasestorage.app',
    measurementId: 'G-QC0V8DYLT9',
  );
}
